#!/usr/bin/env bash
#
# Generated by litx-v{version}.
#
###
set -euo pipefail

# index=0 source=files/example.md:39
export ENV=$1
export AWS_PROFILE=freckle

psql_() {
  ../tools/run-in-ssh psql "$@"
}

# index=1 source=files/example.md:52
psql_ -f ./scripts/upgrade/drop-reg-types.sql

# index=2 source=files/example.md:58
stackctl --filter "..." deploy --no-confirm

# index=3 source=files/example.md:64
psql_ -f ./scripts/upgrade/add-reg-types.sql
