#!/usr/bin/env bash
#
# Generated by litx-v0.0.0.0.
#
###
set -euo pipefail

# source=files/example.md:26
export ENV=$1
export AWS_PROFILE=freckle

psql_() {
  ../tools/run-in-ssh psql "$@"
}

# source=files/example.md:39
psql_ -f ./scripts/upgrade/drop-reg-types.sql

# source=files/example.md:45
stackctl --filter "..." deploy --no-confirm

# source=files/example.md:51
psql_ -f ./scripts/upgrade/add-reg-types.sql
